### ISSUE TITLE
Django version support for Mezzanine-Block

### ISSUE THREAD

**Issue by anurali** [renyi/mezzanine-blocks#23]
Hi,
Mezzanine-blocks on Django=1.8.5  didn't work but on 1.7.10 it worked for me.
Is this version not supported? Is there any updates coming up?

Thanks

**Comment by renyi** [comment]
Hi, is your problem the same as #22 ?

**Comment by anurali** [comment]
I have uninstalled south then it worked on Django=1.7.10.I want to understand if it is supporting the latest version of Django or not,as i don't want to have a restricted version for Mezzanine Blocks which would be an issue on later run.

**Comment by renyi** [comment]
There shouldn't be any issue, except for migrations. And South migrations is needed for Django < 1.8. You can refer to #22 for migration problems.
